#!/bin/bash

# Mudando a temperatura da tela com a aplicação xsct

status="./status"

if [ ! -f "$status" ]; then
    echo "default" > "$status"
fi

temperature=$(cat "$status")

if [ "$temperature" == "default" ]; then
    xsct 5500    
    echo "warm" > "$status"
else
    xsct 6400    
    echo "default" > "$status"
fi
